# Generated by Django 3.0.6 on 2020-07-06 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200706_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='ptitle',
        ),
    ]
