# Generated by Django 3.0.6 on 2020-07-07 06:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0007_auto_20200706_2013'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Postcomment',
            new_name='Blogcomment',
        ),
    ]
