# Generated by Django 3.0.6 on 2020-07-20 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200717_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='auther',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=5000),
        ),
    ]
